#define GMEXPORT extern "C" __declspec(dllexport)
#include "variableWrapper.hpp"
#include "gameMakerFunctions\3DGraphics\d3d_model.hpp"
#include "gameMakerFunctions\3DGraphics\d3d_shape.hpp"
#include "gameMakerFunctions\3DGraphics\d3d_transform.hpp"
#include "gameMakerFunctions\3DGraphics\d3d_primitive.hpp"
#include "gameMakerFunctions\userInteraction\mouse.hpp"
#include "gameMakerFunctions\userInteraction\keyboard.hpp"
#include "gameMakerFunctions\userInteraction\joystick.hpp"
#include "gameMakerFunctions\gameGraphics\fontsAndText.hpp"
#include "gameMakerFunctions\gameGraphics\drawingShapes.hpp"
#include "gameMakerFunctions\gameGraphics\theWindow.hpp"
#include "gameMakerFunctions\gameGraphics\theDisplay.hpp"
#include "gameMakerFunctions\gamePlay\rooms.hpp"
#include "gameMakerFunctions\builtInVariables.hpp"
#include "gameMakerFunctions\customFunctions.hpp"
