double joystick_exists(double id);
void joystick_axes(double id);
double joystick_buttons(double id);
double joystick_has_pov(double id);
double joystick_direction(double id);
double joystick_check_button(double id, double numb);
double joystick_xpos(double id);
double joystick_ypos(double id);
double joystick_zpos(double id);
double joystick_rpos(double id);
double joystick_upos(double id);
double joystick_vpos(double id);
double joystick_pov(double id);
