global.delayCallDLL_export_d3d_model_create = external_define("CallDelayedFunctions.dll", "export_d3d_model_create", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_model_create, scr_wrapper_d3d_model_create);
global.delayCallDLL_export_d3d_model_destroy = external_define("CallDelayedFunctions.dll", "export_d3d_model_destroy", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_model_destroy, scr_wrapper_d3d_model_destroy);
global.delayCallDLL_export_d3d_model_load = external_define("CallDelayedFunctions.dll", "export_d3d_model_load", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_model_load, scr_wrapper_d3d_model_load);
global.delayCallDLL_export_d3d_model_draw = external_define("CallDelayedFunctions.dll", "export_d3d_model_draw", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_model_draw, scr_wrapper_d3d_model_draw);
global.delayCallDLL_export_d3d_model_primitive_begin = external_define("CallDelayedFunctions.dll", "export_d3d_model_primitive_begin", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_model_primitive_begin, scr_wrapper_d3d_model_primitive_begin);
global.delayCallDLL_export_d3d_model_vertex_texture = external_define("CallDelayedFunctions.dll", "export_d3d_model_vertex_texture", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_model_vertex_texture, scr_wrapper_d3d_model_vertex_texture);
global.delayCallDLL_export_d3d_model_primitive_end = external_define("CallDelayedFunctions.dll", "export_d3d_model_primitive_end", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_model_primitive_end, scr_wrapper_d3d_model_primitive_end);
global.delayCallDLL_export_d3d_primitive_begin = external_define("CallDelayedFunctions.dll", "export_d3d_primitive_begin", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_primitive_begin, scr_wrapper_d3d_primitive_begin);
global.delayCallDLL_export_d3d_vertex = external_define("CallDelayedFunctions.dll", "export_d3d_vertex", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_vertex, scr_wrapper_d3d_vertex);
global.delayCallDLL_export_d3d_vertex_color = external_define("CallDelayedFunctions.dll", "export_d3d_vertex_color", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_vertex_color, scr_wrapper_d3d_vertex_color);
global.delayCallDLL_export_d3d_primitive_end = external_define("CallDelayedFunctions.dll", "export_d3d_primitive_end", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_primitive_end, scr_wrapper_d3d_primitive_end);
global.delayCallDLL_export_d3d_primitive_begin_texture = external_define("CallDelayedFunctions.dll", "export_d3d_primitive_begin_texture", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_primitive_begin_texture, scr_wrapper_d3d_primitive_begin_texture);
global.delayCallDLL_export_d3d_vertex_texture = external_define("CallDelayedFunctions.dll", "export_d3d_vertex_texture", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_vertex_texture, scr_wrapper_d3d_vertex_texture);
global.delayCallDLL_export_d3d_vertex_texture_color = external_define("CallDelayedFunctions.dll", "export_d3d_vertex_texture_color", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_vertex_texture_color, scr_wrapper_d3d_vertex_texture_color);
global.delayCallDLL_export_d3d_vertex_normal_color = external_define("CallDelayedFunctions.dll", "export_d3d_vertex_normal_color", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_vertex_normal_color, scr_wrapper_d3d_vertex_normal_color);
global.delayCallDLL_export_d3d_vertex_normal_texture = external_define("CallDelayedFunctions.dll", "export_d3d_vertex_normal_texture", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_vertex_normal_texture, scr_wrapper_d3d_vertex_normal_texture);
global.delayCallDLL_export_d3d_vertex_normal_texture_color = external_define("CallDelayedFunctions.dll", "export_d3d_vertex_normal_texture_color", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_vertex_normal_texture_color, scr_wrapper_d3d_vertex_normal_texture_color);
global.delayCallDLL_export_d3d_draw_block = external_define("CallDelayedFunctions.dll", "export_d3d_draw_block", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_draw_block, scr_wrapper_d3d_draw_block);
global.delayCallDLL_export_d3d_draw_cylinder = external_define("CallDelayedFunctions.dll", "export_d3d_draw_cylinder", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_draw_cylinder, scr_wrapper_d3d_draw_cylinder);
global.delayCallDLL_export_d3d_draw_cone = external_define("CallDelayedFunctions.dll", "export_d3d_draw_cone", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_draw_cone, scr_wrapper_d3d_draw_cone);
global.delayCallDLL_export_d3d_draw_ellipsoid = external_define("CallDelayedFunctions.dll", "export_d3d_draw_ellipsoid", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_draw_ellipsoid, scr_wrapper_d3d_draw_ellipsoid);
global.delayCallDLL_export_d3d_draw_wall = external_define("CallDelayedFunctions.dll", "export_d3d_draw_wall", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_draw_wall, scr_wrapper_d3d_draw_wall);
global.delayCallDLL_export_d3d_draw_floor = external_define("CallDelayedFunctions.dll", "export_d3d_draw_floor", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_draw_floor, scr_wrapper_d3d_draw_floor);
global.delayCallDLL_export_d3d_set_projection_ortho = external_define("CallDelayedFunctions.dll", "export_d3d_set_projection_ortho", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_set_projection_ortho, scr_wrapper_d3d_set_projection_ortho);
global.delayCallDLL_export_d3d_set_projection_perspective = external_define("CallDelayedFunctions.dll", "export_d3d_set_projection_perspective", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_set_projection_perspective, scr_wrapper_d3d_set_projection_perspective);
global.delayCallDLL_export_d3d_set_projection = external_define("CallDelayedFunctions.dll", "export_d3d_set_projection", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_set_projection, scr_wrapper_d3d_set_projection);
global.delayCallDLL_export_d3d_start = external_define("CallDelayedFunctions.dll", "export_d3d_start", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_start, scr_wrapper_d3d_start);
global.delayCallDLL_export_d3d_set_fog = external_define("CallDelayedFunctions.dll", "export_d3d_set_fog", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_set_fog, scr_wrapper_d3d_set_fog);
global.delayCallDLL_export_d3d_set_lighting = external_define("CallDelayedFunctions.dll", "export_d3d_set_lighting", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_set_lighting, scr_wrapper_d3d_set_lighting);
global.delayCallDLL_export_d3d_transform_set_identity = external_define("CallDelayedFunctions.dll", "export_d3d_transform_set_identity", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_transform_set_identity, scr_wrapper_d3d_transform_set_identity);
global.delayCallDLL_export_d3d_transform_set_translation = external_define("CallDelayedFunctions.dll", "export_d3d_transform_set_translation", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_transform_set_translation, scr_wrapper_d3d_transform_set_translation);
global.delayCallDLL_export_d3d_transform_set_scaling = external_define("CallDelayedFunctions.dll", "export_d3d_transform_set_scaling", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_transform_set_scaling, scr_wrapper_d3d_transform_set_scaling);
global.delayCallDLL_export_d3d_transform_set_rotation_x = external_define("CallDelayedFunctions.dll", "export_d3d_transform_set_rotation_x", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_transform_set_rotation_x, scr_wrapper_d3d_transform_set_rotation_x);
global.delayCallDLL_export_d3d_transform_set_rotation_y = external_define("CallDelayedFunctions.dll", "export_d3d_transform_set_rotation_y", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_transform_set_rotation_y, scr_wrapper_d3d_transform_set_rotation_y);
global.delayCallDLL_export_d3d_transform_set_rotation_z = external_define("CallDelayedFunctions.dll", "export_d3d_transform_set_rotation_z", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_transform_set_rotation_z, scr_wrapper_d3d_transform_set_rotation_z);
global.delayCallDLL_export_d3d_transform_set_rotation_axis = external_define("CallDelayedFunctions.dll", "export_d3d_transform_set_rotation_axis", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_transform_set_rotation_axis, scr_wrapper_d3d_transform_set_rotation_axis);
global.delayCallDLL_export_d3d_transform_add_translation = external_define("CallDelayedFunctions.dll", "export_d3d_transform_add_translation", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_transform_add_translation, scr_wrapper_d3d_transform_add_translation);
global.delayCallDLL_export_d3d_transform_add_scaling = external_define("CallDelayedFunctions.dll", "export_d3d_transform_add_scaling", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_transform_add_scaling, scr_wrapper_d3d_transform_add_scaling);
global.delayCallDLL_export_d3d_transform_add_rotation_x = external_define("CallDelayedFunctions.dll", "export_d3d_transform_add_rotation_x", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_transform_add_rotation_x, scr_wrapper_d3d_transform_add_rotation_x);
global.delayCallDLL_export_d3d_transform_add_rotation_y = external_define("CallDelayedFunctions.dll", "export_d3d_transform_add_rotation_y", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_transform_add_rotation_y, scr_wrapper_d3d_transform_add_rotation_y);
global.delayCallDLL_export_d3d_transform_add_rotation_z = external_define("CallDelayedFunctions.dll", "export_d3d_transform_add_rotation_z", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_transform_add_rotation_z, scr_wrapper_d3d_transform_add_rotation_z);
global.delayCallDLL_export_d3d_transform_add_rotation_axis = external_define("CallDelayedFunctions.dll", "export_d3d_transform_add_rotation_axis", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_transform_add_rotation_axis, scr_wrapper_d3d_transform_add_rotation_axis);
global.delayCallDLL_export_draw_text = external_define("CallDelayedFunctions.dll", "export_draw_text", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_draw_text, scr_wrapper_draw_text);
global.delayCallDLL_export_mouse_check_button = external_define("CallDelayedFunctions.dll", "export_mouse_check_button", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_mouse_check_button, scr_wrapper_mouse_check_button);
global.delayCallDLL_export_mouse_check_button_pressed = external_define("CallDelayedFunctions.dll", "export_mouse_check_button_pressed", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_mouse_check_button_pressed, scr_wrapper_mouse_check_button_pressed);
global.delayCallDLL_export_mouse_check_button_released = external_define("CallDelayedFunctions.dll", "export_mouse_check_button_released", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_mouse_check_button_released, scr_wrapper_mouse_check_button_released);
global.delayCallDLL_export_mouse_wheel_up = external_define("CallDelayedFunctions.dll", "export_mouse_wheel_up", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_mouse_wheel_up, scr_wrapper_mouse_wheel_up);
global.delayCallDLL_export_mouse_wheel_down = external_define("CallDelayedFunctions.dll", "export_mouse_wheel_down", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_mouse_wheel_down, scr_wrapper_mouse_wheel_down);
global.delayCallDLL_export_keyboard_check = external_define("CallDelayedFunctions.dll", "export_keyboard_check", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_keyboard_check, scr_wrapper_keyboard_check);
global.delayCallDLL_export_joystick_exists = external_define("CallDelayedFunctions.dll", "export_joystick_exists", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_joystick_exists, scr_wrapper_joystick_exists);
global.delayCallDLL_export_joystick_axes = external_define("CallDelayedFunctions.dll", "export_joystick_axes", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_joystick_axes, scr_wrapper_joystick_axes);
global.delayCallDLL_export_joystick_buttons = external_define("CallDelayedFunctions.dll", "export_joystick_buttons", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_joystick_buttons, scr_wrapper_joystick_buttons);
global.delayCallDLL_export_joystick_has_pov = external_define("CallDelayedFunctions.dll", "export_joystick_has_pov", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_joystick_has_pov, scr_wrapper_joystick_has_pov);
global.delayCallDLL_export_joystick_direction = external_define("CallDelayedFunctions.dll", "export_joystick_direction", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_joystick_direction, scr_wrapper_joystick_direction);
global.delayCallDLL_export_joystick_check_button = external_define("CallDelayedFunctions.dll", "export_joystick_check_button", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_joystick_check_button, scr_wrapper_joystick_check_button);
global.delayCallDLL_export_joystick_xpos = external_define("CallDelayedFunctions.dll", "export_joystick_xpos", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_joystick_xpos, scr_wrapper_joystick_xpos);
global.delayCallDLL_export_joystick_ypos = external_define("CallDelayedFunctions.dll", "export_joystick_ypos", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_joystick_ypos, scr_wrapper_joystick_ypos);
global.delayCallDLL_export_joystick_zpos = external_define("CallDelayedFunctions.dll", "export_joystick_zpos", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_joystick_zpos, scr_wrapper_joystick_zpos);
global.delayCallDLL_export_joystick_rpos = external_define("CallDelayedFunctions.dll", "export_joystick_rpos", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_joystick_rpos, scr_wrapper_joystick_rpos);
global.delayCallDLL_export_joystick_upos = external_define("CallDelayedFunctions.dll", "export_joystick_upos", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_joystick_upos, scr_wrapper_joystick_upos);
global.delayCallDLL_export_joystick_vpos = external_define("CallDelayedFunctions.dll", "export_joystick_vpos", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_joystick_vpos, scr_wrapper_joystick_vpos);
global.delayCallDLL_export_joystick_pov = external_define("CallDelayedFunctions.dll", "export_joystick_pov", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_joystick_pov, scr_wrapper_joystick_pov);
global.delayCallDLL_export_game_end = external_define("CallDelayedFunctions.dll", "export_game_end", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_game_end, scr_wrapper_game_end);
