global.delayCallDLL_export_d3d_model_create = external_define("CallDelayedFunctions.dll", "export_d3d_model_create", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_model_create, scr_wrapper_d3d_model_create);
global.delayCallDLL_export_d3d_model_destroy = external_define("CallDelayedFunctions.dll", "export_d3d_model_destroy", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_model_destroy, scr_wrapper_d3d_model_destroy);
global.delayCallDLL_export_d3d_model_load = external_define("CallDelayedFunctions.dll", "export_d3d_model_load", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_model_load, scr_wrapper_d3d_model_load);
global.delayCallDLL_export_d3d_model_draw = external_define("CallDelayedFunctions.dll", "export_d3d_model_draw", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_model_draw, scr_wrapper_d3d_model_draw);
global.delayCallDLL_export_d3d_model_primitive_begin = external_define("CallDelayedFunctions.dll", "export_d3d_model_primitive_begin", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_model_primitive_begin, scr_wrapper_d3d_model_primitive_begin);
global.delayCallDLL_export_d3d_model_vertex_texture = external_define("CallDelayedFunctions.dll", "export_d3d_model_vertex_texture", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_model_vertex_texture, scr_wrapper_d3d_model_vertex_texture);
global.delayCallDLL_export_d3d_model_primitive_end = external_define("CallDelayedFunctions.dll", "export_d3d_model_primitive_end", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_model_primitive_end, scr_wrapper_d3d_model_primitive_end);
global.delayCallDLL_export_d3d_primitive_begin = external_define("CallDelayedFunctions.dll", "export_d3d_primitive_begin", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_primitive_begin, scr_wrapper_d3d_primitive_begin);
global.delayCallDLL_export_d3d_vertex = external_define("CallDelayedFunctions.dll", "export_d3d_vertex", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_vertex, scr_wrapper_d3d_vertex);
global.delayCallDLL_export_d3d_vertex_color = external_define("CallDelayedFunctions.dll", "export_d3d_vertex_color", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_vertex_color, scr_wrapper_d3d_vertex_color);
global.delayCallDLL_export_d3d_primitive_end = external_define("CallDelayedFunctions.dll", "export_d3d_primitive_end", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_primitive_end, scr_wrapper_d3d_primitive_end);
global.delayCallDLL_export_d3d_primitive_begin_texture = external_define("CallDelayedFunctions.dll", "export_d3d_primitive_begin_texture", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_primitive_begin_texture, scr_wrapper_d3d_primitive_begin_texture);
global.delayCallDLL_export_d3d_vertex_texture = external_define("CallDelayedFunctions.dll", "export_d3d_vertex_texture", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_vertex_texture, scr_wrapper_d3d_vertex_texture);
global.delayCallDLL_export_d3d_vertex_texture_color = external_define("CallDelayedFunctions.dll", "export_d3d_vertex_texture_color", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_vertex_texture_color, scr_wrapper_d3d_vertex_texture_color);
global.delayCallDLL_export_d3d_vertex_normal_color = external_define("CallDelayedFunctions.dll", "export_d3d_vertex_normal_color", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_vertex_normal_color, scr_wrapper_d3d_vertex_normal_color);
global.delayCallDLL_export_d3d_vertex_normal_texture = external_define("CallDelayedFunctions.dll", "export_d3d_vertex_normal_texture", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_vertex_normal_texture, scr_wrapper_d3d_vertex_normal_texture);
global.delayCallDLL_export_d3d_vertex_normal_texture_color = external_define("CallDelayedFunctions.dll", "export_d3d_vertex_normal_texture_color", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_vertex_normal_texture_color, scr_wrapper_d3d_vertex_normal_texture_color);
global.delayCallDLL_export_d3d_draw_block = external_define("CallDelayedFunctions.dll", "export_d3d_draw_block", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_draw_block, scr_wrapper_d3d_draw_block);
global.delayCallDLL_export_d3d_draw_cylinder = external_define("CallDelayedFunctions.dll", "export_d3d_draw_cylinder", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_draw_cylinder, scr_wrapper_d3d_draw_cylinder);
global.delayCallDLL_export_d3d_draw_cone = external_define("CallDelayedFunctions.dll", "export_d3d_draw_cone", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_draw_cone, scr_wrapper_d3d_draw_cone);
global.delayCallDLL_export_d3d_draw_ellipsoid = external_define("CallDelayedFunctions.dll", "export_d3d_draw_ellipsoid", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_draw_ellipsoid, scr_wrapper_d3d_draw_ellipsoid);
global.delayCallDLL_export_d3d_draw_wall = external_define("CallDelayedFunctions.dll", "export_d3d_draw_wall", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_draw_wall, scr_wrapper_d3d_draw_wall);
global.delayCallDLL_export_d3d_draw_floor = external_define("CallDelayedFunctions.dll", "export_d3d_draw_floor", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_draw_floor, scr_wrapper_d3d_draw_floor);
global.delayCallDLL_export_d3d_set_projection_ortho = external_define("CallDelayedFunctions.dll", "export_d3d_set_projection_ortho", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_set_projection_ortho, scr_wrapper_d3d_set_projection_ortho);
global.delayCallDLL_export_d3d_set_projection_perspective = external_define("CallDelayedFunctions.dll", "export_d3d_set_projection_perspective", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_set_projection_perspective, scr_wrapper_d3d_set_projection_perspective);
global.delayCallDLL_export_d3d_set_projection = external_define("CallDelayedFunctions.dll", "export_d3d_set_projection", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_set_projection, scr_wrapper_d3d_set_projection);
global.delayCallDLL_export_d3d_start = external_define("CallDelayedFunctions.dll", "export_d3d_start", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_start, scr_wrapper_d3d_start);
global.delayCallDLL_export_d3d_set_fog = external_define("CallDelayedFunctions.dll", "export_d3d_set_fog", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_set_fog, scr_wrapper_d3d_set_fog);
global.delayCallDLL_export_d3d_set_lighting = external_define("CallDelayedFunctions.dll", "export_d3d_set_lighting", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_set_lighting, scr_wrapper_d3d_set_lighting);
global.delayCallDLL_export_d3d_transform_set_identity = external_define("CallDelayedFunctions.dll", "export_d3d_transform_set_identity", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_transform_set_identity, scr_wrapper_d3d_transform_set_identity);
global.delayCallDLL_export_d3d_transform_set_translation = external_define("CallDelayedFunctions.dll", "export_d3d_transform_set_translation", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_transform_set_translation, scr_wrapper_d3d_transform_set_translation);
global.delayCallDLL_export_d3d_transform_set_scaling = external_define("CallDelayedFunctions.dll", "export_d3d_transform_set_scaling", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_transform_set_scaling, scr_wrapper_d3d_transform_set_scaling);
global.delayCallDLL_export_d3d_transform_set_rotation_x = external_define("CallDelayedFunctions.dll", "export_d3d_transform_set_rotation_x", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_transform_set_rotation_x, scr_wrapper_d3d_transform_set_rotation_x);
global.delayCallDLL_export_d3d_transform_set_rotation_y = external_define("CallDelayedFunctions.dll", "export_d3d_transform_set_rotation_y", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_transform_set_rotation_y, scr_wrapper_d3d_transform_set_rotation_y);
global.delayCallDLL_export_d3d_transform_set_rotation_z = external_define("CallDelayedFunctions.dll", "export_d3d_transform_set_rotation_z", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_transform_set_rotation_z, scr_wrapper_d3d_transform_set_rotation_z);
global.delayCallDLL_export_d3d_transform_set_rotation_axis = external_define("CallDelayedFunctions.dll", "export_d3d_transform_set_rotation_axis", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_transform_set_rotation_axis, scr_wrapper_d3d_transform_set_rotation_axis);
global.delayCallDLL_export_d3d_transform_add_translation = external_define("CallDelayedFunctions.dll", "export_d3d_transform_add_translation", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_transform_add_translation, scr_wrapper_d3d_transform_add_translation);
global.delayCallDLL_export_d3d_transform_add_scaling = external_define("CallDelayedFunctions.dll", "export_d3d_transform_add_scaling", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_transform_add_scaling, scr_wrapper_d3d_transform_add_scaling);
global.delayCallDLL_export_d3d_transform_add_rotation_x = external_define("CallDelayedFunctions.dll", "export_d3d_transform_add_rotation_x", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_transform_add_rotation_x, scr_wrapper_d3d_transform_add_rotation_x);
global.delayCallDLL_export_d3d_transform_add_rotation_y = external_define("CallDelayedFunctions.dll", "export_d3d_transform_add_rotation_y", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_transform_add_rotation_y, scr_wrapper_d3d_transform_add_rotation_y);
global.delayCallDLL_export_d3d_transform_add_rotation_z = external_define("CallDelayedFunctions.dll", "export_d3d_transform_add_rotation_z", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_transform_add_rotation_z, scr_wrapper_d3d_transform_add_rotation_z);
global.delayCallDLL_export_d3d_transform_add_rotation_axis = external_define("CallDelayedFunctions.dll", "export_d3d_transform_add_rotation_axis", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_d3d_transform_add_rotation_axis, scr_wrapper_d3d_transform_add_rotation_axis);
global.delayCallDLL_export_draw_set_font = external_define("CallDelayedFunctions.dll", "export_draw_set_font", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_draw_set_font, scr_wrapper_draw_set_font);
global.delayCallDLL_export_draw_set_halign = external_define("CallDelayedFunctions.dll", "export_draw_set_halign", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_draw_set_halign, scr_wrapper_draw_set_halign);
global.delayCallDLL_export_draw_set_valign = external_define("CallDelayedFunctions.dll", "export_draw_set_valign", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_draw_set_valign, scr_wrapper_draw_set_valign);
global.delayCallDLL_export_draw_text = external_define("CallDelayedFunctions.dll", "export_draw_text", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_draw_text, scr_wrapper_draw_text);
global.delayCallDLL_export_draw_text_ext = external_define("CallDelayedFunctions.dll", "export_draw_text_ext", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_draw_text_ext, scr_wrapper_draw_text_ext);
global.delayCallDLL_export_string_width = external_define("CallDelayedFunctions.dll", "export_string_width", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_string_width, scr_wrapper_string_width);
global.delayCallDLL_export_string_height = external_define("CallDelayedFunctions.dll", "export_string_height", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_string_height, scr_wrapper_string_height);
global.delayCallDLL_export_string_width_ext = external_define("CallDelayedFunctions.dll", "export_string_width_ext", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_string_width_ext, scr_wrapper_string_width_ext);
global.delayCallDLL_export_string_height_ext = external_define("CallDelayedFunctions.dll", "export_string_height_ext", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_string_height_ext, scr_wrapper_string_height_ext);
global.delayCallDLL_export_draw_text_transformed = external_define("CallDelayedFunctions.dll", "export_draw_text_transformed", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_draw_text_transformed, scr_wrapper_draw_text_transformed);
global.delayCallDLL_export_draw_text_ext_transformed = external_define("CallDelayedFunctions.dll", "export_draw_text_ext_transformed", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_draw_text_ext_transformed, scr_wrapper_draw_text_ext_transformed);
global.delayCallDLL_export_draw_text_color = external_define("CallDelayedFunctions.dll", "export_draw_text_color", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_draw_text_color, scr_wrapper_draw_text_color);
global.delayCallDLL_export_draw_text_ext_color = external_define("CallDelayedFunctions.dll", "export_draw_text_ext_color", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_draw_text_ext_color, scr_wrapper_draw_text_ext_color);
global.delayCallDLL_export_draw_text_transformed_color = external_define("CallDelayedFunctions.dll", "export_draw_text_transformed_color", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_draw_text_transformed_color, scr_wrapper_draw_text_transformed_color);
global.delayCallDLL_export_draw_text_ext_transformed_color = external_define("CallDelayedFunctions.dll", "export_draw_text_ext_transformed_color", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_draw_text_ext_transformed_color, scr_wrapper_draw_text_ext_transformed_color);
global.delayCallDLL_export_sprite_get_texture = external_define("CallDelayedFunctions.dll", "export_sprite_get_texture", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_sprite_get_texture, scr_wrapper_sprite_get_texture);
global.delayCallDLL_export_sprite_add = external_define("CallDelayedFunctions.dll", "export_sprite_add", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_sprite_add, scr_wrapper_sprite_add);
global.delayCallDLL_export_draw_sprite = external_define("CallDelayedFunctions.dll", "export_draw_sprite", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_draw_sprite, scr_wrapper_draw_sprite);
global.delayCallDLL_export_show_message = external_define("CallDelayedFunctions.dll", "export_show_message", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_show_message, scr_wrapper_show_message);
global.delayCallDLL_export_draw_clear = external_define("CallDelayedFunctions.dll", "export_draw_clear", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_draw_clear, scr_wrapper_draw_clear);
global.delayCallDLL_export_draw_clear_alpha = external_define("CallDelayedFunctions.dll", "export_draw_clear_alpha", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_draw_clear_alpha, scr_wrapper_draw_clear_alpha);
global.delayCallDLL_export_draw_point = external_define("CallDelayedFunctions.dll", "export_draw_point", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_draw_point, scr_wrapper_draw_point);
global.delayCallDLL_export_draw_line = external_define("CallDelayedFunctions.dll", "export_draw_line", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_draw_line, scr_wrapper_draw_line);
global.delayCallDLL_export_draw_line_width = external_define("CallDelayedFunctions.dll", "export_draw_line_width", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_draw_line_width, scr_wrapper_draw_line_width);
global.delayCallDLL_export_draw_rectangle = external_define("CallDelayedFunctions.dll", "export_draw_rectangle", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_draw_rectangle, scr_wrapper_draw_rectangle);
global.delayCallDLL_export_draw_roundrect = external_define("CallDelayedFunctions.dll", "export_draw_roundrect", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_draw_roundrect, scr_wrapper_draw_roundrect);
global.delayCallDLL_export_draw_triangle = external_define("CallDelayedFunctions.dll", "export_draw_triangle", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_draw_triangle, scr_wrapper_draw_triangle);
global.delayCallDLL_export_draw_circle = external_define("CallDelayedFunctions.dll", "export_draw_circle", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_draw_circle, scr_wrapper_draw_circle);
global.delayCallDLL_export_draw_ellipse = external_define("CallDelayedFunctions.dll", "export_draw_ellipse", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_draw_ellipse, scr_wrapper_draw_ellipse);
global.delayCallDLL_export_draw_set_circle_precision = external_define("CallDelayedFunctions.dll", "export_draw_set_circle_precision", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_draw_set_circle_precision, scr_wrapper_draw_set_circle_precision);
global.delayCallDLL_export_draw_arrow = external_define("CallDelayedFunctions.dll", "export_draw_arrow", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_draw_arrow, scr_wrapper_draw_arrow);
global.delayCallDLL_export_draw_button = external_define("CallDelayedFunctions.dll", "export_draw_button", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_draw_button, scr_wrapper_draw_button);
global.delayCallDLL_export_draw_path = external_define("CallDelayedFunctions.dll", "export_draw_path", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_draw_path, scr_wrapper_draw_path);
global.delayCallDLL_export_draw_healthbar = external_define("CallDelayedFunctions.dll", "export_draw_healthbar", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_draw_healthbar, scr_wrapper_draw_healthbar);
global.delayCallDLL_export_draw_set_color = external_define("CallDelayedFunctions.dll", "export_draw_set_color", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_draw_set_color, scr_wrapper_draw_set_color);
global.delayCallDLL_export_draw_set_alpha = external_define("CallDelayedFunctions.dll", "export_draw_set_alpha", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_draw_set_alpha, scr_wrapper_draw_set_alpha);
global.delayCallDLL_export_draw_get_color = external_define("CallDelayedFunctions.dll", "export_draw_get_color", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_draw_get_color, scr_wrapper_draw_get_color);
global.delayCallDLL_export_draw_get_alpha = external_define("CallDelayedFunctions.dll", "export_draw_get_alpha", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_draw_get_alpha, scr_wrapper_draw_get_alpha);
global.delayCallDLL_export_make_color_rgb = external_define("CallDelayedFunctions.dll", "export_make_color_rgb", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_make_color_rgb, scr_wrapper_make_color_rgb);
global.delayCallDLL_export_make_color_hsv = external_define("CallDelayedFunctions.dll", "export_make_color_hsv", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_make_color_hsv, scr_wrapper_make_color_hsv);
global.delayCallDLL_export_color_get_red = external_define("CallDelayedFunctions.dll", "export_color_get_red", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_color_get_red, scr_wrapper_color_get_red);
global.delayCallDLL_export_color_get_green = external_define("CallDelayedFunctions.dll", "export_color_get_green", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_color_get_green, scr_wrapper_color_get_green);
global.delayCallDLL_export_color_get_blue = external_define("CallDelayedFunctions.dll", "export_color_get_blue", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_color_get_blue, scr_wrapper_color_get_blue);
global.delayCallDLL_export_color_get_hue = external_define("CallDelayedFunctions.dll", "export_color_get_hue", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_color_get_hue, scr_wrapper_color_get_hue);
global.delayCallDLL_export_color_get_saturation = external_define("CallDelayedFunctions.dll", "export_color_get_saturation", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_color_get_saturation, scr_wrapper_color_get_saturation);
global.delayCallDLL_export_color_get_value = external_define("CallDelayedFunctions.dll", "export_color_get_value", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_color_get_value, scr_wrapper_color_get_value);
global.delayCallDLL_export_merge_color = external_define("CallDelayedFunctions.dll", "export_merge_color", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_merge_color, scr_wrapper_merge_color);
global.delayCallDLL_export_draw_getpixel = external_define("CallDelayedFunctions.dll", "export_draw_getpixel", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_draw_getpixel, scr_wrapper_draw_getpixel);
global.delayCallDLL_export_screen_save = external_define("CallDelayedFunctions.dll", "export_screen_save", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_screen_save, scr_wrapper_screen_save);
global.delayCallDLL_export_screen_save_part = external_define("CallDelayedFunctions.dll", "export_screen_save_part", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_screen_save_part, scr_wrapper_screen_save_part);
global.delayCallDLL_export_mouse_check_button = external_define("CallDelayedFunctions.dll", "export_mouse_check_button", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_mouse_check_button, scr_wrapper_mouse_check_button);
global.delayCallDLL_export_mouse_check_button_pressed = external_define("CallDelayedFunctions.dll", "export_mouse_check_button_pressed", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_mouse_check_button_pressed, scr_wrapper_mouse_check_button_pressed);
global.delayCallDLL_export_mouse_check_button_released = external_define("CallDelayedFunctions.dll", "export_mouse_check_button_released", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_mouse_check_button_released, scr_wrapper_mouse_check_button_released);
global.delayCallDLL_export_mouse_wheel_up = external_define("CallDelayedFunctions.dll", "export_mouse_wheel_up", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_mouse_wheel_up, scr_wrapper_mouse_wheel_up);
global.delayCallDLL_export_mouse_wheel_down = external_define("CallDelayedFunctions.dll", "export_mouse_wheel_down", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_mouse_wheel_down, scr_wrapper_mouse_wheel_down);
global.delayCallDLL_export_keyboard_check = external_define("CallDelayedFunctions.dll", "export_keyboard_check", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_keyboard_check, scr_wrapper_keyboard_check);
global.delayCallDLL_export_keyboard_check_pressed = external_define("CallDelayedFunctions.dll", "export_keyboard_check_pressed", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_keyboard_check_pressed, scr_wrapper_keyboard_check_pressed);
global.delayCallDLL_export_keyboard_check_released = external_define("CallDelayedFunctions.dll", "export_keyboard_check_released", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_keyboard_check_released, scr_wrapper_keyboard_check_released);
global.delayCallDLL_export_joystick_exists = external_define("CallDelayedFunctions.dll", "export_joystick_exists", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_joystick_exists, scr_wrapper_joystick_exists);
global.delayCallDLL_export_joystick_axes = external_define("CallDelayedFunctions.dll", "export_joystick_axes", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_joystick_axes, scr_wrapper_joystick_axes);
global.delayCallDLL_export_joystick_buttons = external_define("CallDelayedFunctions.dll", "export_joystick_buttons", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_joystick_buttons, scr_wrapper_joystick_buttons);
global.delayCallDLL_export_joystick_has_pov = external_define("CallDelayedFunctions.dll", "export_joystick_has_pov", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_joystick_has_pov, scr_wrapper_joystick_has_pov);
global.delayCallDLL_export_joystick_direction = external_define("CallDelayedFunctions.dll", "export_joystick_direction", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_joystick_direction, scr_wrapper_joystick_direction);
global.delayCallDLL_export_joystick_check_button = external_define("CallDelayedFunctions.dll", "export_joystick_check_button", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_joystick_check_button, scr_wrapper_joystick_check_button);
global.delayCallDLL_export_joystick_xpos = external_define("CallDelayedFunctions.dll", "export_joystick_xpos", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_joystick_xpos, scr_wrapper_joystick_xpos);
global.delayCallDLL_export_joystick_ypos = external_define("CallDelayedFunctions.dll", "export_joystick_ypos", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_joystick_ypos, scr_wrapper_joystick_ypos);
global.delayCallDLL_export_joystick_zpos = external_define("CallDelayedFunctions.dll", "export_joystick_zpos", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_joystick_zpos, scr_wrapper_joystick_zpos);
global.delayCallDLL_export_joystick_rpos = external_define("CallDelayedFunctions.dll", "export_joystick_rpos", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_joystick_rpos, scr_wrapper_joystick_rpos);
global.delayCallDLL_export_joystick_upos = external_define("CallDelayedFunctions.dll", "export_joystick_upos", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_joystick_upos, scr_wrapper_joystick_upos);
global.delayCallDLL_export_joystick_vpos = external_define("CallDelayedFunctions.dll", "export_joystick_vpos", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_joystick_vpos, scr_wrapper_joystick_vpos);
global.delayCallDLL_export_joystick_pov = external_define("CallDelayedFunctions.dll", "export_joystick_pov", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_joystick_pov, scr_wrapper_joystick_pov);
global.delayCallDLL_export_game_end = external_define("CallDelayedFunctions.dll", "export_game_end", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_game_end, scr_wrapper_game_end);
global.delayCallDLL_export_link_leave_wall = external_define("CallDelayedFunctions.dll", "export_link_leave_wall", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_link_leave_wall, scr_wrapper_link_leave_wall);
global.delayCallDLL_export_get_keyboard_lastkey = external_define("CallDelayedFunctions.dll", "export_get_keyboard_lastkey", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_get_keyboard_lastkey, scr_wrapper_get_keyboard_lastkey);
global.delayCallDLL_export_set_keyboard_lastkey = external_define("CallDelayedFunctions.dll", "export_set_keyboard_lastkey", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_set_keyboard_lastkey, scr_wrapper_set_keyboard_lastkey);
global.delayCallDLL_export_get_mouse_x = external_define("CallDelayedFunctions.dll", "export_get_mouse_x", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_get_mouse_x, scr_wrapper_get_mouse_x);
global.delayCallDLL_export_set_mouse_x = external_define("CallDelayedFunctions.dll", "export_set_mouse_x", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_set_mouse_x, scr_wrapper_set_mouse_x);
global.delayCallDLL_export_get_mouse_y = external_define("CallDelayedFunctions.dll", "export_get_mouse_y", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_get_mouse_y, scr_wrapper_get_mouse_y);
global.delayCallDLL_export_set_mouse_y = external_define("CallDelayedFunctions.dll", "export_set_mouse_y", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_set_mouse_y, scr_wrapper_set_mouse_y);
global.delayCallDLL_export_get_fa_left = external_define("CallDelayedFunctions.dll", "export_get_fa_left", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_get_fa_left, scr_wrapper_get_fa_left);
global.delayCallDLL_export_set_fa_left = external_define("CallDelayedFunctions.dll", "export_set_fa_left", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_set_fa_left, scr_wrapper_set_fa_left);
global.delayCallDLL_export_get_fa_center = external_define("CallDelayedFunctions.dll", "export_get_fa_center", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_get_fa_center, scr_wrapper_get_fa_center);
global.delayCallDLL_export_set_fa_center = external_define("CallDelayedFunctions.dll", "export_set_fa_center", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_set_fa_center, scr_wrapper_set_fa_center);
global.delayCallDLL_export_get_fa_right = external_define("CallDelayedFunctions.dll", "export_get_fa_right", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_get_fa_right, scr_wrapper_get_fa_right);
global.delayCallDLL_export_set_fa_right = external_define("CallDelayedFunctions.dll", "export_set_fa_right", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_set_fa_right, scr_wrapper_set_fa_right);
global.delayCallDLL_export_get_fa_top = external_define("CallDelayedFunctions.dll", "export_get_fa_top", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_get_fa_top, scr_wrapper_get_fa_top);
global.delayCallDLL_export_set_fa_top = external_define("CallDelayedFunctions.dll", "export_set_fa_top", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_set_fa_top, scr_wrapper_set_fa_top);
global.delayCallDLL_export_get_fa_middle = external_define("CallDelayedFunctions.dll", "export_get_fa_middle", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_get_fa_middle, scr_wrapper_get_fa_middle);
global.delayCallDLL_export_set_fa_middle = external_define("CallDelayedFunctions.dll", "export_set_fa_middle", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_set_fa_middle, scr_wrapper_set_fa_middle);
global.delayCallDLL_export_get_fa_bottom = external_define("CallDelayedFunctions.dll", "export_get_fa_bottom", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_get_fa_bottom, scr_wrapper_get_fa_bottom);
global.delayCallDLL_export_set_fa_bottom = external_define("CallDelayedFunctions.dll", "export_set_fa_bottom", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_set_fa_bottom, scr_wrapper_set_fa_bottom);
global.delayCallDLL_export_get_vk_left = external_define("CallDelayedFunctions.dll", "export_get_vk_left", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_get_vk_left, scr_wrapper_get_vk_left);
global.delayCallDLL_export_set_vk_left = external_define("CallDelayedFunctions.dll", "export_set_vk_left", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_set_vk_left, scr_wrapper_set_vk_left);
global.delayCallDLL_export_get_vk_right = external_define("CallDelayedFunctions.dll", "export_get_vk_right", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_get_vk_right, scr_wrapper_get_vk_right);
global.delayCallDLL_export_set_vk_right = external_define("CallDelayedFunctions.dll", "export_set_vk_right", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_set_vk_right, scr_wrapper_set_vk_right);
global.delayCallDLL_export_get_vk_up = external_define("CallDelayedFunctions.dll", "export_get_vk_up", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_get_vk_up, scr_wrapper_get_vk_up);
global.delayCallDLL_export_set_vk_up = external_define("CallDelayedFunctions.dll", "export_set_vk_up", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_set_vk_up, scr_wrapper_set_vk_up);
global.delayCallDLL_export_get_vk_down = external_define("CallDelayedFunctions.dll", "export_get_vk_down", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_get_vk_down, scr_wrapper_get_vk_down);
global.delayCallDLL_export_set_vk_down = external_define("CallDelayedFunctions.dll", "export_set_vk_down", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_set_vk_down, scr_wrapper_set_vk_down);
global.delayCallDLL_export_get_vk_enter = external_define("CallDelayedFunctions.dll", "export_get_vk_enter", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_get_vk_enter, scr_wrapper_get_vk_enter);
global.delayCallDLL_export_set_vk_enter = external_define("CallDelayedFunctions.dll", "export_set_vk_enter", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_set_vk_enter, scr_wrapper_set_vk_enter);
global.delayCallDLL_export_get_vk_escape = external_define("CallDelayedFunctions.dll", "export_get_vk_escape", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_get_vk_escape, scr_wrapper_get_vk_escape);
global.delayCallDLL_export_set_vk_escape = external_define("CallDelayedFunctions.dll", "export_set_vk_escape", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_set_vk_escape, scr_wrapper_set_vk_escape);
global.delayCallDLL_export_get_vk_space = external_define("CallDelayedFunctions.dll", "export_get_vk_space", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_get_vk_space, scr_wrapper_get_vk_space);
global.delayCallDLL_export_set_vk_space = external_define("CallDelayedFunctions.dll", "export_set_vk_space", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_set_vk_space, scr_wrapper_set_vk_space);
global.delayCallDLL_export_get_vk_shift = external_define("CallDelayedFunctions.dll", "export_get_vk_shift", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_get_vk_shift, scr_wrapper_get_vk_shift);
global.delayCallDLL_export_set_vk_shift = external_define("CallDelayedFunctions.dll", "export_set_vk_shift", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_set_vk_shift, scr_wrapper_set_vk_shift);
global.delayCallDLL_export_get_vk_control = external_define("CallDelayedFunctions.dll", "export_get_vk_control", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_get_vk_control, scr_wrapper_get_vk_control);
global.delayCallDLL_export_set_vk_control = external_define("CallDelayedFunctions.dll", "export_set_vk_control", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_set_vk_control, scr_wrapper_set_vk_control);
global.delayCallDLL_export_get_pr_pointlist = external_define("CallDelayedFunctions.dll", "export_get_pr_pointlist", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_get_pr_pointlist, scr_wrapper_get_pr_pointlist);
global.delayCallDLL_export_set_pr_pointlist = external_define("CallDelayedFunctions.dll", "export_set_pr_pointlist", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_set_pr_pointlist, scr_wrapper_set_pr_pointlist);
global.delayCallDLL_export_get_pr_linelist = external_define("CallDelayedFunctions.dll", "export_get_pr_linelist", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_get_pr_linelist, scr_wrapper_get_pr_linelist);
global.delayCallDLL_export_set_pr_linelist = external_define("CallDelayedFunctions.dll", "export_set_pr_linelist", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_set_pr_linelist, scr_wrapper_set_pr_linelist);
global.delayCallDLL_export_get_pr_linestrip = external_define("CallDelayedFunctions.dll", "export_get_pr_linestrip", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_get_pr_linestrip, scr_wrapper_get_pr_linestrip);
global.delayCallDLL_export_set_pr_linestrip = external_define("CallDelayedFunctions.dll", "export_set_pr_linestrip", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_set_pr_linestrip, scr_wrapper_set_pr_linestrip);
global.delayCallDLL_export_get_pr_trianglelist = external_define("CallDelayedFunctions.dll", "export_get_pr_trianglelist", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_get_pr_trianglelist, scr_wrapper_get_pr_trianglelist);
global.delayCallDLL_export_set_pr_trianglelist = external_define("CallDelayedFunctions.dll", "export_set_pr_trianglelist", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_set_pr_trianglelist, scr_wrapper_set_pr_trianglelist);
global.delayCallDLL_export_get_pr_trianglestrip = external_define("CallDelayedFunctions.dll", "export_get_pr_trianglestrip", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_get_pr_trianglestrip, scr_wrapper_get_pr_trianglestrip);
global.delayCallDLL_export_set_pr_trianglestrip = external_define("CallDelayedFunctions.dll", "export_set_pr_trianglestrip", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_set_pr_trianglestrip, scr_wrapper_set_pr_trianglestrip);
global.delayCallDLL_export_get_pr_trianglefan = external_define("CallDelayedFunctions.dll", "export_get_pr_trianglefan", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_get_pr_trianglefan, scr_wrapper_get_pr_trianglefan);
global.delayCallDLL_export_set_pr_trianglefan = external_define("CallDelayedFunctions.dll", "export_set_pr_trianglefan", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_set_pr_trianglefan, scr_wrapper_set_pr_trianglefan);
global.delayCallDLL_export_get_tex_2DLink = external_define("CallDelayedFunctions.dll", "export_get_tex_2DLink", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_get_tex_2DLink, scr_wrapper_get_tex_2DLink);
global.delayCallDLL_export_set_tex_2DLink = external_define("CallDelayedFunctions.dll", "export_set_tex_2DLink", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_set_tex_2DLink, scr_wrapper_set_tex_2DLink);
global.delayCallDLL_export_get_tex_SMB_pipe = external_define("CallDelayedFunctions.dll", "export_get_tex_SMB_pipe", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_get_tex_SMB_pipe, scr_wrapper_get_tex_SMB_pipe);
global.delayCallDLL_export_set_tex_SMB_pipe = external_define("CallDelayedFunctions.dll", "export_set_tex_SMB_pipe", dll_cdecl, ty_real, 1, ty_real);
external_call(global.delayCallDLL_export_set_tex_SMB_pipe, scr_wrapper_set_tex_SMB_pipe);
