void draw_clear(double col);
void draw_clear_alpha(double col,double alpha);
void draw_point(double x,double y);
void draw_line(double x1,double y1,double x2,double y2);
void draw_line_width(double x1,double y1,double x2,double y2,double w);
void draw_rectangle(double x1,double y1,double x2,double y2,double outline);
void draw_roundrect(double x1,double y1,double x2,double y2,double outline);
void draw_triangle(double x1,double y1,double x2,double y2,double x3,double y3,double outline);
void draw_circle(double x,double y,double r,double outline);
void draw_ellipse(double x1,double y1,double x2,double y2,double outline);
void draw_set_circle_precision(double precision);
void draw_arrow(double x1,double y1,double x2,double y2,double size);
void draw_button(double x1,double y1,double x2,double y2,double up);
void draw_path(double path,double x,double y,double absolute);
void draw_healthbar(double x1,double y1,double x2,double y2,double amount,double backcol,double mincol,double maxcol,double direction,double showback,double showborder);
void draw_set_color(double col);
void draw_set_alpha(double alpha);
double draw_get_color();
double draw_get_alpha();
double make_color_rgb(double red,double green,double blue);
double make_color_hsv(double hue,double saturation,double value);
double color_get_red(double col);
double color_get_green(double col);
double color_get_blue(double col);
double color_get_hue(double col);
double color_get_saturation(double col);
double color_get_value(double col);
double merge_color(double col1,double col2,double amount);
double draw_getpixel(double x,double y);
void screen_save(const char* fname);
void screen_save_part(const char* fname,double x,double y,double w,double h);
