void draw_set_font(double font);
void draw_set_halign(double halign);
void draw_set_valign(double valign);
void draw_text(double x, double y, const char* string);
void draw_text_ext(double x, double y, const char* string, double sep, double w);
double string_width(const char* string);
double string_height(const char* string);
double string_width_ext(const char* string, double sep, double w);
double string_height_ext(const char* string, double sep, double w);
void draw_text_transformed(double x, double y, const char* string, double xscale, double yscale, double angle);
void draw_text_ext_transformed(double x, double y, const char* string, double sep, double w, double xscale, double yscale, double angle);
void draw_text_color(double x, double y, const char* string, double c1, double c2, double c3, double c4, double alpha);
void draw_text_ext_color(double x, double y, const char* string, double sep, double w, double c1, double c2, double c3, double c4, double alpha);
void draw_text_transformed_color(double x, double y, const char* string, double xscale, double yscale, double angle, double c1, double c2, double c3, double c4, double alpha);
void draw_text_ext_transformed_color(double x, double y, const char* string, double sep, double w, double xscale, double yscale, double angle, double c1, double c2, double c3, double c4, double alpha);
double sprite_get_texture(double spr, double subimg);
double sprite_add(const char* fname, double imgnumb, double removeback, double smooth, double xorig, double yorig);
void draw_sprite(double spr, double subimg, double x, double y);
double show_message(const char* text_string);
